// src/pages/GoodsDetail/index.jsx
import React, { Component } from 'react'
import qs from 'qs'
import style from './style.scss'
import LazyLoad from 'react-lazyload'
import { Link } from 'react-router-dom'
import { resizeImg } from '../../common/utils'
import CargoSource from '../../api/CargoSource'

class GoodsDetail extends Component {
    constructor(props) {
        super(props)
        this.state = {
            goodsDetail: {}
        }
        this.query = qs.parse(this.props.location.search, { ignoreQueryPrefix: true })
    }
    componentWillMount() {
        this.getInfo()
    }
    getInfo() {
        CargoSource.findById({
            id: this.query.id,
            AppId: this.query.AppId || ''
        }).then(res => {
            this.setState({ goodsDetail: res })
        })
    }
    render() {
        return (
            <div>
                <div className={`${style.baseInfo} bdtb`}>
                    <LazyLoad height={70}>
                        <img className={style.pic} width="70" src={resizeImg(this.state.goodsDetail.headPicture, '_150x150.')} alt=""/>
                    </LazyLoad>
                    <p>
                        <b className={style.name}>{this.state.goodsDetail.realName}</b>
                        <span className={style.attention}>
                            {
                                this.state.goodsDetail.certifyStatus === 'Success' 
                                ? <img src={require('../../assets/icons/attention.svg')} alt=""/> 
                                : ''
                            }    
                        </span>
                    </p>
                    <p className={style.history}>
                        历史发货
                        <span className="c1">{this.state.goodsDetail.cargoSourceNum}</span>
                        条
                    </p>
                    <a className={style.tel} href="'tel:' + goodsDetail.mobile">
                        <img src={require('../../assets/icons/ic_call_phone_image.png')} alt="" />
                    </a>
                </div>
                <div className="cells bdtb">
                    <div className="cell">
                        <div className={style.cell__hd}>
                            <img className={style.icon} src={require('../../assets/icons/local_icon.svg')} alt="" />
                        </div>
                        <div className={`${style.cell__bd} ${style.lineInfo}`}>
                            <span className={style.start}>
                            {
                                this.state.goodsDetail.areaFromName 
                                ? (this.state.goodsDetail.areaFromName.split(',').length === 4 
                                    ? this.state.goodsDetail.areaFromName.split(',')[1] + this.state.goodsDetail.areaFromName.split(',')[2] 
                                    : this.state.goodsDetail.areaFromName.split(',')[0] + this.state.goodsDetail.areaFromName.split(',')[1]) : ''
                            }
                            </span>
                            <span className={style.arrow}></span>
                            <span className={style.end}>
                            {
                                this.state.goodsDetail.areaToName 
                                ? (this.state.goodsDetail.areaToName.split(',').length === 4 
                                    ? this.state.goodsDetail.areaToName.split(',')[1] + this.state.goodsDetail.areaToName.split(',')[2] 
                                    : this.state.goodsDetail.areaToName.split(',')[0] + this.state.goodsDetail.areaToName.split(',')[1]) : ''
                            }
                            </span>
                        </div>
                    </div>
                </div>
                <Link className={`${style.viewMap} bdtb`} to={{
                    pathname: 'goodsLine', 
                    search: `?areaFromLat=${this.state.goodsDetail.areaFromLat}
                            &areaFromLng=${this.state.goodsDetail.areaFromLng}
                            &areaToLat=${this.state.goodsDetail.areaToLat}
                            &areaToLng=${this.state.goodsDetail.areaToLng}`
                }}>
                    <img src={require('../../assets/img/line.jpg')} width="100%" alt="" />
                    <p>最短里程<b>{(this.state.goodsDetail.estimateMileage || 0) + '公里'}</b></p>
                </Link>
                <div className="cells bdtb">
                    <div className="cell">
                        <div className={style.cell__hd}>
                            <img className={style.icon} src={require('../../assets/icons/detail_icon1.svg')} alt="" />
                        </div>
                        <div className={style.cell__bd}>
                            <label className={style.labels}>装车时间</label>
                            <span>{this.state.goodsDetail.loadingDateStr?this.state.goodsDetail.loadingDateStr:''}</span>
                        </div>
                    </div>
                    <div className="cell bdt">
                        <div className={style.cell__hd}>
                            <img className={style.icon} src={require('../../assets/icons/package.svg')} alt="" />
                        </div>
                        <div className={style.cell__bd}>
                            <label className={style.labels}>货物信息</label>
                            <span className="c1">
                                {this.state.goodsDetail.cargoName}/
                                {
                                    [
                                        this.state.goodsDetail.cargoWeight ? this.state.goodsDetail.cargoWeight + '吨' : '',
                                        this.state.goodsDetail.cargoVolume ? this.state.goodsDetail.cargoVolume + '方' : '',
                                        this.state.goodsDetail.cargoNum ? this.state.goodsDetail.cargoNum + '件' : ''
                                    ].filter(item => item).join('/')
                                }
                            </span>
                        </div>
                    </div>
                    <div className="cell bdt">
                        <div className={style.cell__hd}>
                            <img className={style.icon} src={require('../../assets/icons/truckDesc_icon.svg')} alt="" />
                        </div>
                        <div className={style.cell__bd}>
                            <label className={style.labels}>需求车辆</label>
                            <span className="c1">
                            {
                                [
                                    this.state.goodsDetail.truckLengthName,
                                    this.state.goodsDetail.truckTypeName,
                                    ('剩' + this.state.goodsDetail.surplusTruckNum + '车')
                                ].join('/')
                            }
                            </span>
                        </div>
                    </div>
                    <div className="cell bdt">
                        <div className={style.cell__hd}>
                            <img className={style.icon} src={require('../../assets/icons/detail_icon5.svg')} alt="" />
                        </div>
                        <div className={style.cell__bd}>
                            <label className={style.labels}>货主留言</label>
                            <span>{this.state.goodsDetail.remarkName}</span>
                        </div>
                    </div>
                </div>
                <div className={style.padd}>
                    <Link className={style.btn} to={{
                        pathname: 'AppDownloadRichTxt', 
                        search: `?AppId=${this.query.AppId}` 
                    }}>
                        {
                            this.state.goodsDetail.cargoFreightType === 'Fix' 
                            ? (<div><img src={require('../../assets/icons/truck.svg')} alt=""/>我要承运</div>) 
                            : (this.state.goodsDetail.cargoFreightType === 'Talk' 
                                ? (<div><img src={require('../../assets/icons/rmb.svg')} alt=""/>我要报价</div>) 
                                : (<div><img src={require('../../assets/icons/rmb.svg')} alt=""/>支付信息费</div>))
                        }
                    </Link>
                </div>
            </div>
        )
    }
}

export default GoodsDetail

// src/components/goodsDetail.vue
<template>
	<div>
		<div class="container">
			<!-- <div class="titleBar">货源详情</div> -->
			<div class="baseInfo bdb">
				<img v-if="goodsDetail.headPicture" :src='__IMGWEBSERVER__ + goodsDetail.headPicture' class="pic" @error="errorImg"/>
			    <p>
			    	<b class="name">{{goodsDetail.realName}}</b>
			    	<span class="attention">
						<img src="../assets/img/attention.svg" v-if="goodsDetail.certifyStatus == 'Success'"/>
					</span>
			    </p>
			    <!-- <p class="company">云南微服物流</p> -->
			    <p class="history">历史发货<span class="c1">{{goodsDetail.cargoSourceNum}}</span>条</p>
			    <router-link tag="div" :to="{name: 'AppDownload'}" class="tel"><img src="../assets/img/ic_call_phone_image.png"/></router-link>
			</div>
			</div>
			<div class="cells bdtb">
				<div class="cell">
					<div class="cell__hd">
						<img class="icon" src="../assets/img/local_icon.svg">
					</div>
					<div class="cell__bd lineInfo">
						<span class="start">{{goodsDetail.areaFromName?(goodsDetail.areaFromName.split(',').length == 4 ? goodsDetail.areaFromName.split(',')[1] + goodsDetail.areaFromName.split(',')[2] : goodsDetail.areaFromName.split(',')[0] + goodsDetail.areaFromName.split(',')[1]):''}}</span>
						<span class="arrow"></span>
						<span class="end">{{goodsDetail.areaToName?(goodsDetail.areaToName.split(',').length == 4 ? goodsDetail.areaToName.split(',')[1]+goodsDetail.areaToName.split(',')[2] :goodsDetail.areaToName.split(',')[0] + goodsDetail.areaToName.split(',')[1]):''}}</span>
					</div>
				</div>
			</div>
			<router-link tag="div" class="viewMap bdtb" :to="{name: 'goodsLine', query: {areaFromLat: goodsDetail.areaFromLat, areaFromLng: goodsDetail.areaFromLng, areaToLat: goodsDetail.areaToLat, areaToLng: goodsDetail.areaToLng}}">
				<img src="../../static/img/line.jpg" width="100%" />
				<p>最短里程<b>{{goodsDetail.estimateMileage < 1000 ? (goodsDetail.estimateMileage + '米') : ((goodsDetail.estimateMileage/1000).toFixed(1) + '公里')}}</b></p>
			</router-link>
			<div class="cells bdtb">
				<div class="cell">
					<div class="cell__hd"><img class="icon" src="../assets/img/detail_icon1.svg"></div>
					<div class="cell__bd"><label class="labels">装车时间</label><span>{{goodsDetail.loadingDateStr?goodsDetail.loadingDateStr:''}}</span></div>
				</div>
				<div class="cell bdt">
					<div class="cell__hd"><img class="icon" src="../assets/img/package.svg"></div>
					<div class="cell__bd">
						<label class="labels">货物信息</label>
						<span class="c1">{{goodsDetail.cargoName}}{{(goodsDetail.cargoWeight !='' && goodsDetail.cargoWeight !='0')?'/'+goodsDetail.cargoWeight+'吨':''}}{{(goodsDetail.cargoVolume !='' && goodsDetail.cargoVolume !='0')?'/'+goodsDetail.cargoVolume+'方':''}}{{(goodsDetail.cargoNum !='' && goodsDetail.cargoNum != '0')?'/'+goodsDetail.cargoNum+'件':''}}</span>
					</div>
				</div>
				<div class="cell bdt">
					<div class="cell__hd"><img class="icon" src="../assets/img/truckDesc_icon.svg"></div>
					<div class="cell__bd">
						<label class="labels">需求车辆</label>
						<span class="c1">{{goodsDetail.truckLengthName||0}}/{{goodsDetail.truckTypeName}}/剩<b>{{goodsDetail.surplusTruckNum}}</b>车</span>
					</div>
				</div>
				<div class="cell bdt">
					<div class="cell__hd"><img class="icon" src="../assets/img/detail_icon5.svg"></div>
					<div class="cell__bd"><label class="labels">货主留言</label><span>{{goodsDetail.remarkName}}</span></div>
				</div>
			</div>
			<div class="padd">
				<router-link tag="div" :to="{name: 'AppDownload'}" class="btn">
					<span v-if="goodsDetail.cargoFreightType == 'Fix'"><img src="../assets/img/truck.svg"/>我要承运</span>
					<span v-else-if="goodsDetail.cargoFreightType == 'Talk'"><img src="../assets/img/rmb.svg"/>我要报价</span>
					<span v-else><img src="../assets/img/rmb.svg"/>支付信息费</span>
				</router-link>
			</div>
		</div>
	</div>
</template>
<script type="text/javascript">
	import {defaultImg} from '../assets/data/icons'
	export default {
		data () {
			return {
				goodsDetail: {}
			}
		},
		created () {
			document.title = '货源详情'
			this.getGoodsDetail()
		},
		methods: {
			getGoodsDetail() {
				let URL = this.__WEBSERVER__ + 'adv/cargoSource/detail'
				let params = {
					"id": this.$route.query.id
				}
				this.$http.get(URL, {params: params}).then(res => {
					console.log(JSON.stringify(res.body.data))
					this.goodsDetail = res.body.data
				})
			},
			errorImg (e) {
                e.target.src = defaultImg
                e.target.onerror = null
            }
		}
	}
</script>
<style lang="stylus" scoped>
	.titleBar
		background #6cc
		height 44px
		line-height 44px
		text-align center
		color #fff
	.baseInfo
		background #fff
		padding 10px 15px 10px 85px
		position relative
		height 80px
		color #999
		font-size 14px
		.pic
			position absolute
			left 15px
			top 10px
			border-radius 4px
			width 60px
			height 60px
		.name
			font-size 16px
			color #666
			font-weight bold
		.history
			margin-top 15px
			span
				padding 0 5px
		.attention
		.user_sort
		.name
			display inline-block
			vertical-align top
			margin-right 5px
			img
				width 20px
				height 20px
		.user_sort
			text-align center
			border-radius 8px
			padding:1px 8px
			color #fff
			&.user_sort1
				background #6cc
			&.user_sort2
				background #5182e5
			&.user_sort3
				background #fcab20
			&.user_sort4
				background #fcab20
		.tel
			position absolute
			right 15px
			top 50%
			width 40px
			height 40px
			transform translateY(-50%)
			-webkit-transform translateY(-50%)
			img
				width 100%
	.viewMap
		background #fff
		margin-top 10px
		position relative
		color #666
		font-weight bold
		font-size 14px
		position relative
		img
			vertical-align top
		p
			height 20px
			line-height 20px
			position absolute
			top 50%
			margin-top -10px
			left 10px
	.cell__hd
		.icon
			vertical-align top
			width 14px
			height 14px
			margin-top 5px
	.cell__bd
		color #666
		position relative
		padding-left 80px
		&.lineInfo
			font-weight bold
			color #666
			position relative
			padding-left 0
			span
				text-overflow ellipsis
				overflow hidden
				white-space nowrap
				display block
				float left
				font-size 14px
		span
			display inline-block
			vertical-align top
			line-height 24px
			b
				color #f60
				padding 0 5px
			&.arrow
				background url('../assets/img/arrow.svg') no-repeat center
				width 30px
				height 24px
				background-size cover
		.labels
			width 80px
			color #999
			position absolute
			left 0
			top 0
			display inline-block
			vertical-align middle
	.btn
		color #fff
		height 44px
		line-height 44px
		border-radius 4px
		background #f60
		text-align center
		img
			height 20px
			vertical-align middle
			margin -2px 5px 0 0					
</style>
